#!/bin/bash
# feedback-loop init - one-time setup. Writes ~/.config/feedback-loop/env from answers/env.
# Non-interactive: pre-set FEEDBACK_PRODUCT_REPO and optional FEEDBACK_INSTANCE_GUIDANCE.
# FEEDBACK_WF_CMD (automated-researcher#468): optional wf.sh resolution when aar-engineering is installed
# but not on PATH - agents repeatedly concluded wf.sh didn't exist because nothing recorded where it lives.
# Nothing is uploaded; config stays local, chmod 600.
set -euo pipefail

CFG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/feedback-loop"
CFG="$CFG_DIR/env"

IN_FEEDBACK_PRODUCT_REPO=${FEEDBACK_PRODUCT_REPO-}
IN_FEEDBACK_INSTANCE_GUIDANCE=${FEEDBACK_INSTANCE_GUIDANCE-}
IN_FEEDBACK_WF_CMD=${FEEDBACK_WF_CMD-}

if [ -f "$CFG" ]; then
  # shellcheck disable=SC1090
  set +u
  . "$CFG"
  set -u
fi

[ -n "$IN_FEEDBACK_PRODUCT_REPO" ] && FEEDBACK_PRODUCT_REPO=$IN_FEEDBACK_PRODUCT_REPO
[ -n "$IN_FEEDBACK_INSTANCE_GUIDANCE" ] && FEEDBACK_INSTANCE_GUIDANCE=$IN_FEEDBACK_INSTANCE_GUIDANCE
[ -n "$IN_FEEDBACK_WF_CMD" ] && FEEDBACK_WF_CMD=$IN_FEEDBACK_WF_CMD

ask_required() {
  local var=$1 prompt=$2 val
  val=${!var:-}
  if [ -z "$val" ] && [ -t 0 ]; then
    read -rp "$prompt: " val
  fi
  [ -n "$val" ] || {
    echo "ERROR: $var required. Set $var=OWNER/REPO or run interactively." >&2
    exit 1
  }
  printf -v "$var" '%s' "$val"
}

ask_optional() {
  local var=$1 prompt=$2 val entered
  val=${!var:-}
  if [ -t 0 ]; then
    read -rp "$prompt${val:+ [$val]}: " entered
    val=${entered:-$val}
  fi
  printf -v "$var" '%s' "$val"
}

ask_required FEEDBACK_PRODUCT_REPO "Product feedback repo (OWNER/REPO)"
case "$FEEDBACK_PRODUCT_REPO" in
  */*) ;;
  *) echo "ERROR: FEEDBACK_PRODUCT_REPO must look like OWNER/REPO" >&2; exit 1 ;;
esac
if ! [[ "$FEEDBACK_PRODUCT_REPO" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]]; then
  echo "ERROR: FEEDBACK_PRODUCT_REPO contains unsupported characters: $FEEDBACK_PRODUCT_REPO" >&2
  exit 1
fi

ask_optional FEEDBACK_INSTANCE_GUIDANCE "Instance feedback guidance path or URI (optional)"
ask_optional FEEDBACK_WF_CMD "wf.sh command, if not on PATH (optional, e.g. an absolute path to aar-engineering's wf.sh)"

umask 077
mkdir -p "$CFG_DIR"
tmp=$(mktemp "$CFG_DIR/env.XXXXXX")
cleanup() { rm -f "$tmp"; }
trap cleanup EXIT

{
  echo "# feedback-loop local config. Generated by feedback_loop_init.sh."
  printf 'FEEDBACK_PRODUCT_REPO=%q\n' "$FEEDBACK_PRODUCT_REPO"
  if [ -n "${FEEDBACK_INSTANCE_GUIDANCE:-}" ]; then
    printf 'FEEDBACK_INSTANCE_GUIDANCE=%q\n' "$FEEDBACK_INSTANCE_GUIDANCE"
  fi
  if [ -n "${FEEDBACK_WF_CMD:-}" ]; then
    printf 'FEEDBACK_WF_CMD=%q\n' "$FEEDBACK_WF_CMD"
  fi
} > "$tmp"
chmod 600 "$tmp"
mv "$tmp" "$CFG"
trap - EXIT

echo "== feedback-loop config written to $CFG (chmod 600) =="
